version: "3.7"
services:
  app:
    image: registry.int.janelia.org/jacs/workstation-status
    restart: unless-stopped
    volumes:
        - ./:/api
        - static_volume:/api/static
    environment:
      - PYTHONUNBUFFERED=1
    networks:
        - workstation-status-net
    ports:
      - 80:8000

networks:
  workstation-status-net:
      driver: bridge

volumes:
  static_volume:
